CREATE TABLE user (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role int NOT NULL,
  name varchar(40),
  password varchar(255)
);
CREATE TABLE permission (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(40),
  role int NOT NULL
);
CREATE TABLE time_entry (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar(512),
  start_time timestamp,
  duration int NOT NULL,
  user_id int NOT NULL
);
CREATE TABLE user_setting (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time time NOT NULL,
  end_time time NOT NULL,
  user_id int NOT NULL,
  UNIQUE(user_id)
);
CREATE TABLE user_session (
  guid VARCHAR(36),
  user_id int NOT NULL
);
